name: youtube_player_flutter
publish_to: none
description: Flutter plugin for playing or streaming inline YouTube videos using the official iFrame player API. This plugin supports both Android and iOS.
version: 8.0.0
repository: https://github.com/sarbagyastha/youtube_player_flutter
homepage: https://github.com/sarbagyastha/youtube_player_flutter/tree/master/packages/youtube_player_flutter


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.16.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview:
    git:
      url: https://github.com/ntkha05/flutter_inappwebview.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/speedometer.webp